name: 'Deploy to Netlify'

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the website
        run: |
          mkdir -p /home/runner/work/_temp/_github_home/build
          npm ci
          npm run build
          mv ./build /home/runner/work/_temp/_github_home
      - name: Deploy Netlify
        uses: danakim/gh-action-deploy-netlify@master
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_PROD: true
